### ISSUE TITLE
Making links on side navbar hover with transition

### ISSUE THREAD

**Issue by MohitNamdev22** [AyushSarode/LearningApp#53] opened 2022-10-19 04:49 UTC
On the links of the Side Navbar, there is no hover & transition effect. Can I work on this?
![image](https://user-images.githubusercontent.com/89779447/196600254-14ec06e0-3898-484b-8f04-94d593256247.png)

**Comment by AyushSarode** [comment] 2022-10-19 12:59
Sure. 
Also before creating PR make sure to send screenshot or short video of your changes

**Comment by Supratim30** [comment] 2022-10-20 14:43
Please assign it to me. If the issue is still open.

**Comment by AyushSarode** [comment] 2022-10-20 16:31
Sure

**Comment by MohitNamdev22** [comment] 2022-10-20 16:32
@AyushSarode I've already started working on it and just need to make an PR

**Comment by AyushSarode** [comment] 2022-10-20 16:40
> @AyushSarode I've already started working on it and just need to make an PR

Can you make PR tmrw?

**Comment by MohitNamdev22** [comment] 2022-10-20 16:42
> > @AyushSarode I've already started working on it and just need to make an PR
> 
> Can you make PR tmrw?

Yeah sure
Within an hour

**Comment by AyushSarode** [comment] 2022-10-20 16:44
> > > @AyushSarode I've already started working on it and just need to make an PR
> > 
> > 
> > Can you make PR tmrw?
> 
> Yeah sure Within an hour

Thanks!

**Comment by MohitNamdev22** [comment] 2022-10-20 16:57
@AyushSarode I've raised my PR kindly review and merge it.

**Closed** 2022-10-21 18:51 UTC
Labels: hacktoberfest
